# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/src/greenhouse_data_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/src/greenhouse_data_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/src/greenhouse_data_server/CMakeFiles /home/pi/src/greenhouse_data_server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/src/greenhouse_data_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named greenhouse_data_server

# Build rule for target.
greenhouse_data_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greenhouse_data_server
.PHONY : greenhouse_data_server

# fast build rule for target.
greenhouse_data_server/fast:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/build
.PHONY : greenhouse_data_server/fast

src/APWeatherDataManager.o: src/APWeatherDataManager.cpp.o
.PHONY : src/APWeatherDataManager.o

# target to build an object file
src/APWeatherDataManager.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/APWeatherDataManager.cpp.o
.PHONY : src/APWeatherDataManager.cpp.o

src/APWeatherDataManager.i: src/APWeatherDataManager.cpp.i
.PHONY : src/APWeatherDataManager.i

# target to preprocess a source file
src/APWeatherDataManager.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/APWeatherDataManager.cpp.i
.PHONY : src/APWeatherDataManager.cpp.i

src/APWeatherDataManager.s: src/APWeatherDataManager.cpp.s
.PHONY : src/APWeatherDataManager.s

# target to generate assembly for a file
src/APWeatherDataManager.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/APWeatherDataManager.cpp.s
.PHONY : src/APWeatherDataManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/util/APException.o: src/util/APException.cpp.o
.PHONY : src/util/APException.o

# target to build an object file
src/util/APException.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APException.cpp.o
.PHONY : src/util/APException.cpp.o

src/util/APException.i: src/util/APException.cpp.i
.PHONY : src/util/APException.i

# target to preprocess a source file
src/util/APException.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APException.cpp.i
.PHONY : src/util/APException.cpp.i

src/util/APException.s: src/util/APException.cpp.s
.PHONY : src/util/APException.s

# target to generate assembly for a file
src/util/APException.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APException.cpp.s
.PHONY : src/util/APException.cpp.s

src/util/APSQLException.o: src/util/APSQLException.cpp.o
.PHONY : src/util/APSQLException.o

# target to build an object file
src/util/APSQLException.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSQLException.cpp.o
.PHONY : src/util/APSQLException.cpp.o

src/util/APSQLException.i: src/util/APSQLException.cpp.i
.PHONY : src/util/APSQLException.i

# target to preprocess a source file
src/util/APSQLException.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSQLException.cpp.i
.PHONY : src/util/APSQLException.cpp.i

src/util/APSQLException.s: src/util/APSQLException.cpp.s
.PHONY : src/util/APSQLException.s

# target to generate assembly for a file
src/util/APSQLException.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSQLException.cpp.s
.PHONY : src/util/APSQLException.cpp.s

src/util/APSimpleJSONQuery.o: src/util/APSimpleJSONQuery.cpp.o
.PHONY : src/util/APSimpleJSONQuery.o

# target to build an object file
src/util/APSimpleJSONQuery.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSimpleJSONQuery.cpp.o
.PHONY : src/util/APSimpleJSONQuery.cpp.o

src/util/APSimpleJSONQuery.i: src/util/APSimpleJSONQuery.cpp.i
.PHONY : src/util/APSimpleJSONQuery.i

# target to preprocess a source file
src/util/APSimpleJSONQuery.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSimpleJSONQuery.cpp.i
.PHONY : src/util/APSimpleJSONQuery.cpp.i

src/util/APSimpleJSONQuery.s: src/util/APSimpleJSONQuery.cpp.s
.PHONY : src/util/APSimpleJSONQuery.s

# target to generate assembly for a file
src/util/APSimpleJSONQuery.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSimpleJSONQuery.cpp.s
.PHONY : src/util/APSimpleJSONQuery.cpp.s

src/util/APSimpleSQL.o: src/util/APSimpleSQL.cpp.o
.PHONY : src/util/APSimpleSQL.o

# target to build an object file
src/util/APSimpleSQL.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSimpleSQL.cpp.o
.PHONY : src/util/APSimpleSQL.cpp.o

src/util/APSimpleSQL.i: src/util/APSimpleSQL.cpp.i
.PHONY : src/util/APSimpleSQL.i

# target to preprocess a source file
src/util/APSimpleSQL.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSimpleSQL.cpp.i
.PHONY : src/util/APSimpleSQL.cpp.i

src/util/APSimpleSQL.s: src/util/APSimpleSQL.cpp.s
.PHONY : src/util/APSimpleSQL.s

# target to generate assembly for a file
src/util/APSimpleSQL.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/util/APSimpleSQL.cpp.s
.PHONY : src/util/APSimpleSQL.cpp.s

src/weather_sources/APDarkSkyForcastIO.o: src/weather_sources/APDarkSkyForcastIO.cpp.o
.PHONY : src/weather_sources/APDarkSkyForcastIO.o

# target to build an object file
src/weather_sources/APDarkSkyForcastIO.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APDarkSkyForcastIO.cpp.o
.PHONY : src/weather_sources/APDarkSkyForcastIO.cpp.o

src/weather_sources/APDarkSkyForcastIO.i: src/weather_sources/APDarkSkyForcastIO.cpp.i
.PHONY : src/weather_sources/APDarkSkyForcastIO.i

# target to preprocess a source file
src/weather_sources/APDarkSkyForcastIO.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APDarkSkyForcastIO.cpp.i
.PHONY : src/weather_sources/APDarkSkyForcastIO.cpp.i

src/weather_sources/APDarkSkyForcastIO.s: src/weather_sources/APDarkSkyForcastIO.cpp.s
.PHONY : src/weather_sources/APDarkSkyForcastIO.s

# target to generate assembly for a file
src/weather_sources/APDarkSkyForcastIO.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APDarkSkyForcastIO.cpp.s
.PHONY : src/weather_sources/APDarkSkyForcastIO.cpp.s

src/weather_sources/APOpenWeatherMap.o: src/weather_sources/APOpenWeatherMap.cpp.o
.PHONY : src/weather_sources/APOpenWeatherMap.o

# target to build an object file
src/weather_sources/APOpenWeatherMap.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APOpenWeatherMap.cpp.o
.PHONY : src/weather_sources/APOpenWeatherMap.cpp.o

src/weather_sources/APOpenWeatherMap.i: src/weather_sources/APOpenWeatherMap.cpp.i
.PHONY : src/weather_sources/APOpenWeatherMap.i

# target to preprocess a source file
src/weather_sources/APOpenWeatherMap.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APOpenWeatherMap.cpp.i
.PHONY : src/weather_sources/APOpenWeatherMap.cpp.i

src/weather_sources/APOpenWeatherMap.s: src/weather_sources/APOpenWeatherMap.cpp.s
.PHONY : src/weather_sources/APOpenWeatherMap.s

# target to generate assembly for a file
src/weather_sources/APOpenWeatherMap.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APOpenWeatherMap.cpp.s
.PHONY : src/weather_sources/APOpenWeatherMap.cpp.s

src/weather_sources/APWeatherSource.o: src/weather_sources/APWeatherSource.cpp.o
.PHONY : src/weather_sources/APWeatherSource.o

# target to build an object file
src/weather_sources/APWeatherSource.cpp.o:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APWeatherSource.cpp.o
.PHONY : src/weather_sources/APWeatherSource.cpp.o

src/weather_sources/APWeatherSource.i: src/weather_sources/APWeatherSource.cpp.i
.PHONY : src/weather_sources/APWeatherSource.i

# target to preprocess a source file
src/weather_sources/APWeatherSource.cpp.i:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APWeatherSource.cpp.i
.PHONY : src/weather_sources/APWeatherSource.cpp.i

src/weather_sources/APWeatherSource.s: src/weather_sources/APWeatherSource.cpp.s
.PHONY : src/weather_sources/APWeatherSource.s

# target to generate assembly for a file
src/weather_sources/APWeatherSource.cpp.s:
	$(MAKE) -f CMakeFiles/greenhouse_data_server.dir/build.make CMakeFiles/greenhouse_data_server.dir/src/weather_sources/APWeatherSource.cpp.s
.PHONY : src/weather_sources/APWeatherSource.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... greenhouse_data_server"
	@echo "... rebuild_cache"
	@echo "... src/APWeatherDataManager.o"
	@echo "... src/APWeatherDataManager.i"
	@echo "... src/APWeatherDataManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/util/APException.o"
	@echo "... src/util/APException.i"
	@echo "... src/util/APException.s"
	@echo "... src/util/APSQLException.o"
	@echo "... src/util/APSQLException.i"
	@echo "... src/util/APSQLException.s"
	@echo "... src/util/APSimpleJSONQuery.o"
	@echo "... src/util/APSimpleJSONQuery.i"
	@echo "... src/util/APSimpleJSONQuery.s"
	@echo "... src/util/APSimpleSQL.o"
	@echo "... src/util/APSimpleSQL.i"
	@echo "... src/util/APSimpleSQL.s"
	@echo "... src/weather_sources/APDarkSkyForcastIO.o"
	@echo "... src/weather_sources/APDarkSkyForcastIO.i"
	@echo "... src/weather_sources/APDarkSkyForcastIO.s"
	@echo "... src/weather_sources/APOpenWeatherMap.o"
	@echo "... src/weather_sources/APOpenWeatherMap.i"
	@echo "... src/weather_sources/APOpenWeatherMap.s"
	@echo "... src/weather_sources/APWeatherSource.o"
	@echo "... src/weather_sources/APWeatherSource.i"
	@echo "... src/weather_sources/APWeatherSource.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

