//
// Created by David Trotz on 5/15/16.
//

#ifndef GREENHOUSE_DATA_SERVER_APWEATHERSOURCE_H
#define GREENHOUSE_DATA_SERVER_APWEATHERSOURCE_H


class APWeatherSource {

};


#endif //GREENHOUSE_DATA_SERVER_APWEATHERSOURCE_H
